apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: default
data:
  # General configuration for all services
  REDIS_URL: "redis-service.default.svc.cluster.local:6379"
  KAFKA_BROKERS: "kafka-service.default.svc.cluster.local:9092"
  NODE_ENV: "production"
